export enum ServicesSettings {
  BANK_SERVICE = 'BANK_SERVICE',
  TRANSACTIONS_SERVICE = 'TRANSACTIONS_SERVICE',
  DATA_SERVICE = 'DATA_SERVICE',
  INTERNET_SERVICE = 'INTERNET_SERVICE',
  AIRTIME_SERVICE = 'AIRTIME_SERVICE',
  ELECTRICITY_SERVICE = 'ELECTRICITY_SERVICE',
  CABLETV_SERVICE = 'CABLETV_SERVICE',
  EDUCATION_SERVICE = 'EDUCATION_SERVICE',
}

export type ServiceSettingsType = keyof Record<ServicesSettings, string>;
